_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R_50.pkl"
  RESNETS:
    DEPTH: 50
  DIFFUSIONDET:
    # --- CẤU HÌNH NHIỀU NHÃN CHO DENTAL ---
    NUM_CLASSES: 33           
    NUM_CLASSES_PATHO: 4      
    NUM_CLASSES_JAW: 2        
    
    # Contrastive Loss
    CONTRA_WEIGHT: 5.0
    CONTRA_TEMP: 0.07

    # Số lượng hộp box khuếch tán
    NUM_PROPOSALS: 300 
    
    # Bước tinh chỉnh mẫu trong lúc dự đoán
    SAMPLE_STEP: 1            
DATASETS:
  TRAIN: ("caries_train",)
  TEST: ("caries_val",)
DATALOADER:
  NUM_WORKERS: 2              
SOLVER:
  REFRH: 0
  IMS_PER_BATCH: 4            
  BASE_LR: 0.00005            
  STEPS: (20000, 24000)
  MAX_ITER: 30000             
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000
  WEIGHT_DECAY: 0.0001
  OPTIMIZER: "ADAMW"

INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1333
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
